<a href="https://colab.research.google.com/github/jetendarsoothar-png/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jetendarsoothar-png/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [45]:
conn.sql("SHOW TABLES").df()

Empty DataFrame
Columns: [name]
Index: []

In [46]:
conn.sql("""
SELECT *
FROM glob('hf://datasets/FlyRank/internship-warehouse/**')
LIMIT 20
""").df()

                                                 file
0   hf://datasets/FlyRank/internship-warehouse/.gi...
1   hf://datasets/FlyRank/internship-warehouse/REA...
2   hf://datasets/FlyRank/internship-warehouse/dim...
3   hf://datasets/FlyRank/internship-warehouse/dim...
4   hf://datasets/FlyRank/internship-warehouse/fac...
5   hf://datasets/FlyRank/internship-warehouse/fac...
6   hf://datasets/FlyRank/internship-warehouse/fac...
7   hf://datasets/FlyRank/internship-warehouse/fac...
8   hf://datasets/FlyRank/internship-warehouse/fac...
9   hf://datasets/FlyRank/internship-warehouse/fac...
10  hf://datasets/FlyRank/internship-warehouse/fac...
11  hf://datasets/FlyRank/internship-warehouse/fac...
12  hf://datasets/FlyRank/internship-warehouse/fac...
13  hf://datasets/FlyRank/internship-warehouse/fac...
14  hf://datasets/FlyRank/internship-warehouse/fac...
15  hf://datasets/FlyRank/internship-warehouse/fac...
16  hf://datasets/FlyRank/internship-warehouse/fac...
17  hf://datasets/FlyRank/internship-warehouse/fac...
18  hf://datasets/FlyRank/internship-warehouse/fac...
19  hf://datasets/FlyRank/internship-warehouse/fac...

In [47]:
files = conn.sql("""
SELECT file
FROM glob('hf://datasets/FlyRank/internship-warehouse/**')
WHERE file LIKE '%.parquet'
ORDER BY file
""").df()

files

                                                 file
0   hf://datasets/FlyRank/internship-warehouse/dim...
1   hf://datasets/FlyRank/internship-warehouse/dim...
2   hf://datasets/FlyRank/internship-warehouse/fac...
3   hf://datasets/FlyRank/internship-warehouse/fac...
4   hf://datasets/FlyRank/internship-warehouse/fac...
5   hf://datasets/FlyRank/internship-warehouse/fac...
6   hf://datasets/FlyRank/internship-warehouse/fac...
7   hf://datasets/FlyRank/internship-warehouse/fac...
8   hf://datasets/FlyRank/internship-warehouse/fac...
9   hf://datasets/FlyRank/internship-warehouse/fac...
10  hf://datasets/FlyRank/internship-warehouse/fac...
11  hf://datasets/FlyRank/internship-warehouse/fac...
12  hf://datasets/FlyRank/internship-warehouse/fac...
13  hf://datasets/FlyRank/internship-warehouse/fac...
14  hf://datasets/FlyRank/internship-warehouse/fac...
15  hf://datasets/FlyRank/internship-warehouse/fac...
16  hf://datasets/FlyRank/internship-warehouse/fac...
17  hf://datasets/FlyRank/internship-warehouse/fac...
18  hf://datasets/FlyRank/internship-warehouse/fac...
19  hf://datasets/FlyRank/internship-warehouse/fac...
20  hf://datasets/FlyRank/internship-warehouse/fac...
21  hf://datasets/FlyRank/internship-warehouse/fac...

In [48]:
for f in files["file"]:
    print(f)

hf://datasets/FlyRank/internship-warehouse/dim_clients.parquet
hf://datasets/FlyRank/internship-warehouse/dim_content.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-01/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-02/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-03/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-04/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-05/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-06/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-07/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-08/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-09/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-10/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-11/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2025-12/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-01/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-02/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-03/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-04/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-05/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-06/data_0.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance_sample.parquet
hf://datasets/FlyRank/internship-warehouse/fact_content_query_90d.parquet

In [49]:
march_path = "hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-03/data_0.parquet"

conn.sql(f"""
DESCRIBE SELECT *
FROM read_parquet('{march_path}')
""").df()

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

In [50]:
conn.sql(f"""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT report_date || '|' || client_hash_id || '|' || content_hash_id) AS distinct_grain_rows
FROM read_parquet('{march_path}')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows  distinct_grain_rows
0     9841378              9841378

In [51]:
conn.sql("""
DESCRIBE
SELECT *
FROM read_parquet('hf://datasets/FlyRank/internship-warehouse/dim_content.parquet')
""").df()

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

In [52]:
conn.sql("""
DESCRIBE
SELECT *
FROM read_parquet('hf://datasets/FlyRank/internship-warehouse/dim_clients.parquet')
""").df()

           column_name column_type null   key default extra
0       client_hash_id     VARCHAR  YES  None    None  None
1            is_active     BOOLEAN  YES  None    None  None
2       has_gsc_access     BOOLEAN  YES  None    None  None
3       has_ga4_access     BOOLEAN  YES  None    None  None
4       access_profile     VARCHAR  YES  None    None  None
5  client_created_date        DATE  YES  None    None  None
6  client_updated_date        DATE  YES  None    None  None
7       gsc_data_start        DATE  YES  None    None  None
8       ga4_data_start        DATE  YES  None    None  None

## 1. Unit of analysis + time window
**Unit of analysis:** One row represents one content item for one client on one report date.

**Time window:** I use March 2026 (`2026-03-01` to `2026-03-31`) as the decision-month slice. The future outcome window is April 2026.

In [53]:
conn.sql(f"""
SELECT

    MAX(report_date) AS max_report_date,
    COUNT(DISTINCT report_date) AS number_of_days
FROM read_parquet('{march_path}')
""").df()

  max_report_date  number_of_days
0      2026-03-31              31

In [54]:
conn.sql(f"""
SELECT
    MIN(report_date) AS min_report_date,
    MAX(report_date) AS max_report_date,
    COUNT(DISTINCT report_date) AS number_of_days
FROM read_parquet('{march_path}')
""").df()

  min_report_date max_report_date  number_of_days
0      2026-03-01      2026-03-31              31

## 2. Fields: feature / label / context / excluded

### Features
- `search_volume` — keyword demand known at the decision moment.
- `competition` — keyword competition known at the decision moment.
- `backlinks` — existing backlink count known at the decision moment.
- `word_count` — current content length known at the decision moment.
- `content_age_days` — calculated from content creation date and decision date.

### Label
- Future organic sessions — the future outcome proxy used to rank content.

### Context
- `client_hash_id` — identifies the client.
- `content_hash_id` — identifies the content item.
- `report_date` — identifies the observation date.
- `gsc_data_available` — indicates whether GSC data is available.
- `ga4_data_available` — indicates whether GA4 data is available.

### Excluded
- Future-period performance fields — excluded because they would reveal information from the outcome window and cause leakage.

In [55]:
conn.sql(f"""
SELECT
    COUNT(gsc_impressions) AS non_null_gsc_impressions,
    COUNT(gsc_avg_position) AS non_null_gsc_avg_position,
    COUNT(ga4_sessions) AS non_null_ga4_sessions,
    COUNT(sessions_organic) AS non_null_organic_sessions,
    COUNT(sessions_ai) AS non_null_ai_sessions
FROM read_parquet('{march_path}')
""").df()

,non_null_gsc_impressions,non_null_gsc_avg_position,non_null_ga4_sessions,non_null_organic_sessions,non_null_ai_sessions
0,9841378,3611061,6822637,6822637,6822637

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [56]:
conn.sql(f"""
SELECT
    COUNT(*) = COUNT(DISTINCT report_date || '|' || client_hash_id || '|' || content_hash_id) AS grain_verified
FROM read_parquet('{march_path}')
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   grain_verified
0            True

In [57]:
conn.sql(f"""
SELECT
    COUNT(*) AS row_count,
    MIN(report_date) AS start_date,
    MAX(report_date) AS end_date,
    COUNT(DISTINCT report_date) AS days
FROM read_parquet('{march_path}')
""").df()

   row_count start_date   end_date  days
0    9841378 2026-03-01 2026-03-31    31

In [58]:
conn.sql(f"""
SELECT
    COUNT(*) AS total_rows,
    COUNT(*) FILTER (WHERE gsc_data_available IS TRUE) AS gsc_available_rows,
    COUNT(*) FILTER (WHERE ga4_data_available IS TRUE) AS ga4_available_rows,
    COUNT(*) FILTER (
        WHERE gsc_data_available IS TRUE
           OR ga4_data_available IS TRUE
    ) AS any_source_available_rows
FROM read_parquet('{march_path}')
""").df()

,total_rows,gsc_available_rows,ga4_available_rows,any_source_available_rows
0,9841378,3611061,413966,3660680

## 4. Data limits

This slice cannot tell us why a content item performed well or poorly. The history is also unbalanced because some clients may have GSC or GA4 data available for only part of the period. Therefore, the results are directional and should be used for decision-support rather than treated as causal conclusions. Future outcome windows can also overlap with the period used to create features, so the time boundary must be kept explicit.

### Five features and availability

| Feature | Available when? |
|---|---|
| `search_volume` | Knowable at the decision moment because it comes from the keyword data available before the future outcome window. |
| `competition` | Knowable at the decision moment because keyword competition is an existing search-market attribute. |
| `backlinks` | Knowable at the decision moment because the existing backlink count can be observed before the outcome period. |
| `word_count` | Knowable at the decision moment because the content's current word count is known before future performance is observed. |
| `content_age_days` | Knowable at the decision moment because it is calculated from the content creation date and the decision date. |

In [59]:
march_path = "hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-03/data_0.parquet"

feature_frame = conn.sql(f"""
SELECT
    f.client_hash_id,
    f.content_hash_id,
    f.report_date,

    c.search_volume,
    c.competition,
    c.backlinks,
    c.word_count,

    DATE_DIFF(
        'day',
        c.content_created_date,
        f.report_date
    ) AS content_age_days

FROM read_parquet('{march_path}') AS f

LEFT JOIN read_parquet(
    'hf://datasets/FlyRank/internship-warehouse/dim_content.parquet'
) AS c
    ON f.client_hash_id = c.client_hash_id
   AND f.content_hash_id = c.content_hash_id

WHERE f.gsc_data_available IS TRUE
   OR f.ga4_data_available IS TRUE
""").df()

print("Feature frame shape:", feature_frame.shape)
feature_frame.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Feature frame shape: (3660680, 8)

,client_hash_id,content_hash_id,report_date,search_volume,competition,backlinks,word_count,content_age_days
0,client_62f4a7e64f5e0096,content_2e6360ad20fd7107,2026-03-01,10,0.0,0,2855,17
1,client_62f4a7e64f5e0096,content_ac8663da7484669a,2026-03-01,10,0.0,0,3281,17
2,client_62f4a7e64f5e0096,content_39d7361b4945d504,2026-03-01,10,0.0,0,3579,17
3,client_62f4a7e64f5e0096,content_d49a012dcb924e31,2026-03-01,10,0.0,0,2993,17
4,client_62f4a7e64f5e0096,content_614baf2af4330bd7,2026-03-01,10,0.0,0,3500,17

In [60]:
april_path = "hf://datasets/FlyRank/internship-warehouse/fact_content_daily_performance/month=2026-04/data_0.parquet"

label_frame = conn.sql(f"""
SELECT
    client_hash_id,
    content_hash_id,
    SUM(sessions_organic) AS future_organic_sessions
FROM read_parquet('{april_path}')
GROUP BY
    client_hash_id,
    content_hash_id
""").df()

print("Label frame shape:", label_frame.shape)
label_frame.head()

Label frame shape: (362172, 3)

            client_hash_id           content_hash_id  future_organic_sessions
0  client_62f4a7e64f5e0096  content_ddbfb1907979759a                      NaN
1  client_62f4a7e64f5e0096  content_19d31b32f74b4f12                      NaN
2  client_62f4a7e64f5e0096  content_92bc8dfb830d0ade                      NaN
3  client_62f4a7e64f5e0096  content_2a44e78f3d53769e                      NaN
4  client_62f4a7e64f5e0096  content_745efcdf75e0ec8c                      NaN

In [61]:
model_frame = feature_frame.merge(
    label_frame,
    on=["client_hash_id", "content_hash_id"],
    how="left"
)

model_frame["future_organic_sessions"] = (
    model_frame["future_organic_sessions"].fillna(0)
)

print("Model frame shape:", model_frame.shape)
model_frame.head()

Model frame shape: (3660680, 9)

,client_hash_id,content_hash_id,report_date,search_volume,competition,backlinks,word_count,content_age_days,future_organic_sessions
0,client_62f4a7e64f5e0096,content_2e6360ad20fd7107,2026-03-01,10,0.0,0,2855,17,0.0
1,client_62f4a7e64f5e0096,content_ac8663da7484669a,2026-03-01,10,0.0,0,3281,17,0.0
2,client_62f4a7e64f5e0096,content_39d7361b4945d504,2026-03-01,10,0.0,0,3579,17,0.0
3,client_62f4a7e64f5e0096,content_d49a012dcb924e31,2026-03-01,10,0.0,0,2993,17,0.0
4,client_62f4a7e64f5e0096,content_614baf2af4330bd7,2026-03-01,10,0.0,0,3500,17,0.0

In [62]:
import numpy as np
import pandas as pd

feature_cols = [
    "search_volume",
    "competition",
    "backlinks",
    "word_count",
    "content_age_days"
]

score_df = model_frame[
    feature_cols + ["future_organic_sessions"]
].dropna().copy()

# Limit computation to a reproducible sample
score_sample = score_df.sample(
    n=min(100000, len(score_df)),
    random_state=42
)

correlations = (
    score_sample.corr(numeric_only=True)["future_organic_sessions"]
    .drop("future_organic_sessions")
    .sort_values(key=abs, ascending=False)
)

honest_score = correlations.abs().max()

print("Honest baseline score:", round(honest_score, 4))
print("\nFeature correlations:")
print(correlations)

Honest baseline score: 0.0321

Feature correlations:
competition        -0.032131
word_count          0.025541
content_age_days    0.021515
search_volume      -0.006753
backlinks          -0.003358
Name: future_organic_sessions, dtype: float64

In [63]:
leak_df = score_sample.copy()

# Deliberate leakage: copy the future label into a feature
leak_df["leaked_future_organic_sessions"] = (
    leak_df["future_organic_sessions"]
)

leak_score = leak_df[
    ["leaked_future_organic_sessions", "future_organic_sessions"]
].corr().iloc[0, 1]

print("Leaked score:", round(leak_score, 4))

Leaked score: 1.0

In [64]:
# Remove the deliberately leaked label-derived column
clean_df = leak_df.drop(
    columns=["leaked_future_organic_sessions"]
)

clean_correlations = (
    clean_df.corr(numeric_only=True)["future_organic_sessions"]
    .drop("future_organic_sessions")
    .sort_values(key=abs, ascending=False)
)

honest_score_final = clean_correlations.abs().max()

print("Honest score after removing leakage:",
      round(honest_score_final, 4))

print("\nLeakage lesson:")
print("The leaked score was artificially perfect because the label itself was used as a feature.")
print("The final honest score excludes the label-derived column.")

Honest score after removing leakage: 0.0321

Leakage lesson:
The leaked score was artificially perfect because the label itself was used as a feature.
The final honest score excludes the label-derived column.

### Final self-check

- [x] Contract answers are filled in plain words.
- [x] Exactly three verification queries are included.
- [x] Availability is checked using `IS TRUE`.
- [x] Five features are defined with an "available when?" explanation.
- [x] Future organic sessions is used as the outcome proxy.
- [x] A deliberate label-leakage experiment was performed.
- [x] The leaked feature was removed from the final clean feature set.
- [x] The final score excludes the leaked feature.
- [x] One limitation of the data slice is documented.
- [ ] Notebook runs top to bottom without errors.
- [ ] Notebook is committed under `work/notebooks/w03_data_contract.ipynb`.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.